[package]
name = "urdma-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
ffi = { path = "../urdma-ibverbs-binding", package = "urdma-ibverbs-binding", version = "0.1.0" }

env_logger = "0.11.6"
log = "0.4.25"
